# Generated by Django 3.2.8 on 2021-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='attatchment',
            field=models.FileField(default=None, upload_to='attatchments'),
            preserve_default=False,
        ),
    ]
