# Generated by Django 3.2.8 on 2021-11-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjects_attatchment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='attatchment',
            field=models.FileField(upload_to='documents'),
        ),
    ]
