# Generated by Django 3.2.8 on 2021-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20211103_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
