# Generated by Django 3.2.8 on 2021-11-04 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subjects_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='rating',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='attatchment',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
